-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  Customize your app:
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
local APP_NAME    = "Delightful Qt Web Shell"
local APP_SLUG    = "delightful-qt-web-shell"
local APP_VERSION = "0.1.0"
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

set_project(APP_SLUG)
set_version(APP_VERSION)

add_rules("mode.release")
set_defaultmode("release")
set_languages("c++23")

if is_plat("windows") then
    set_runtimes("MD")
end

add_requires("catch2 3.x")

-- ── Desktop app (Qt WebEngine + React) ───────────────────────────────

target("desktop")
    set_kind("binary")
    add_rules("qt.widgetapp")
    add_files(
        "cpp/main.cpp",
        "cpp/bridge.hpp",
        "cpp/resources/resources.qrc",
        "cpp/web_dist_resources.cpp"
    )
    if is_plat("windows") then
        set_filename(APP_NAME .. ".exe")
        add_files("resources/app.rc")
    elseif is_plat("macosx") then
        set_filename(APP_NAME)
    else
        set_filename(APP_SLUG)
    end
    add_frameworks(
        "QtWidgets", "QtCore", "QtGui",
        "QtWebEngineCore", "QtWebEngineWidgets", "QtWebChannel"
    )
    add_defines('APP_NAME="' .. APP_NAME:gsub('"', '\\"') .. '"')
    add_defines('APP_SLUG="' .. APP_SLUG:gsub('"', '\\"') .. '"')

    before_build(function(target)
        local base = os.scriptdir()
        local web_dir = path.join(base, "web")
        local dist_dir = path.join(web_dir, "dist")

        -- Pass APP_NAME to Vite so index.html and React can use it
        os.setenv("VITE_APP_NAME", APP_NAME)

        -- 1. Build the web app
        os.execv("bun", {"install"}, {curdir = web_dir})
        os.execv("bun", {"run", "build"}, {curdir = web_dir})

        -- 2. Generate a .qrc listing every file in dist/
        local qrc_lines = {'<RCC>', '    <qresource prefix="/web">'}
        for _, f in ipairs(os.files(path.join(dist_dir, "**"))) do
            local rel = path.relative(f, dist_dir):gsub("\\", "/")
            local abs = path.absolute(f):gsub("\\", "/")
            table.insert(qrc_lines, '        <file alias="' .. rel .. '">' .. abs .. '</file>')
        end
        table.insert(qrc_lines, '    </qresource>')
        table.insert(qrc_lines, '</RCC>')

        local qrc_path = path.join(base, "cpp", "web_dist.qrc")
        io.writefile(qrc_path, table.concat(qrc_lines, "\n") .. "\n")

        -- 3. Compile the .qrc into a .cpp via rcc
        --    Windows: bin/rcc.exe    macOS/Linux: libexec/rcc (since Qt 6.1)
        local qt_dir = target:data("qt.dir") or get_config("qt")
        local rcc
        if is_host("windows") then
            rcc = path.join(qt_dir, "bin", "rcc.exe")
        else
            rcc = path.join(qt_dir, "libexec", "rcc")
            if not os.isfile(rcc) then
                rcc = path.join(qt_dir, "bin", "rcc")
            end
        end
        local cpp_path = path.join(base, "cpp", "web_dist_resources.cpp")
        os.runv(rcc, {"-o", cpp_path, qrc_path})

        -- 4. Generate Windows resource file (app.rc) from APP_NAME/APP_SLUG
        if is_plat("windows") then
            local version = APP_VERSION
            local version_parts = version:split("%.") or {"0", "1", "0"}
            local v1 = version_parts[1] or "0"
            local v2 = version_parts[2] or "1"
            local v3 = version_parts[3] or "0"
            local rc_content = '// Auto-generated by xmake — do not edit manually\n'
                .. '#include <windows.h>\n\n'
                .. 'IDI_ICON1 ICON "icon.ico"\n\n'
                .. 'VS_VERSION_INFO VERSIONINFO\n'
                .. '    FILEVERSION    ' .. v1 .. ',' .. v2 .. ',' .. v3 .. ',0\n'
                .. '    PRODUCTVERSION ' .. v1 .. ',' .. v2 .. ',' .. v3 .. ',0\n'
                .. '    FILEFLAGSMASK  VS_FFI_FILEFLAGSMASK\n'
                .. '    FILEFLAGS      0\n'
                .. '    FILEOS         VOS_NT_WINDOWS32\n'
                .. '    FILETYPE       VFT_APP\n'
                .. '    FILESUBTYPE    VFT2_UNKNOWN\n'
                .. 'BEGIN\n'
                .. '    BLOCK "StringFileInfo"\n'
                .. '    BEGIN\n'
                .. '        BLOCK "040904B0"\n'
                .. '        BEGIN\n'
                .. '            VALUE "FileDescription",  "' .. APP_NAME .. '"\n'
                .. '            VALUE "FileVersion",      "' .. version .. '"\n'
                .. '            VALUE "InternalName",     "' .. APP_SLUG .. '"\n'
                .. '            VALUE "OriginalFilename", "' .. APP_NAME .. '.exe"\n'
                .. '            VALUE "ProductName",      "' .. APP_NAME .. '"\n'
                .. '            VALUE "ProductVersion",   "' .. version .. '"\n'
                .. '        END\n'
                .. '    END\n'
                .. '    BLOCK "VarFileInfo"\n'
                .. '    BEGIN\n'
                .. '        VALUE "Translation", 0x0409, 0x04B0\n'
                .. '    END\n'
                .. 'END\n'
            io.writefile(path.join(base, "resources", "app.rc"), rc_content)
        end
    end)

    after_build(function(target)
        local base = os.scriptdir()
        local binary_path = target:targetfile()
        io.writefile(path.join(base, "build", ".desktop-binary.txt"), binary_path)
    end)

-- ── C++ unit tests (Catch2, no Qt) ───────────────────────────────────

target("test-todo-store")
    set_kind("binary")
    set_default(false)
    add_files("tests/todo_store_test.cpp")
    add_packages("catch2")

-- ── Headless WebSocket test server (Qt, no GUI) ──────────────────────

target("test-server")
    set_kind("binary")
    set_default(false)
    add_rules("qt.console")
    add_files(
        "cpp/test_server.cpp",
        "cpp/bridge.hpp",
        "cpp/expose_as_ws.hpp"
    )
    add_frameworks("QtCore", "QtNetwork", "QtWebSockets")

-- ── Playwright e2e tests ─────────────────────────────────────────────

target("test-e2e")
    set_kind("phony")
    set_default(false)
    on_run(function()
        print(">>> npx playwright test (e2e)")
        local base = os.scriptdir()
        os.execv("npx", {"playwright", "test", "--project=e2e"}, {curdir = base})
    end)

-- ── Playwright CDP smoke tests (real Qt app) ─────────────────────────

target("test-smoke")
    set_kind("phony")
    set_default(false)
    on_run(function()
        print(">>> npx playwright test (smoke)")
        local base = os.scriptdir()
        os.execv("npx", {"playwright", "test", "--project=smoke"}, {curdir = base})
    end)

-- ── Bun unit tests ───────────────────────────────────────────────────

target("test-bun")
    set_kind("phony")
    set_default(false)
    on_run(function()
        print(">>> bun test")
        local base = os.scriptdir()
        os.execv("bun", {"test"}, {curdir = base})
    end)

-- ── Run all tests ────────────────────────────────────────────────────

target("test-all")
    set_kind("phony")
    set_default(false)
    on_run(function()
        print(">>> Catch2: TodoStore unit tests")
        os.execv("xmake", {"run", "test-todo-store"})
        print("")
        print(">>> Bun: bridge proxy unit tests")
        os.execv("xmake", {"run", "test-bun"})
        print("")
        print(">>> Playwright: e2e tests (C++ backend)")
        os.execv("xmake", {"run", "test-e2e"})
    end)
