target("lib.todos")
    set_kind("headeronly")
    add_includedirs("include", {public = true})
    add_packages("def_type", {public = true})

target("lib.todos.test")
    set_kind("binary")
    set_default(false)
    add_deps("lib.todos")
    add_files("tests/unit/todo_store_test.cpp")
    add_packages("catch2")
    set_rundir("$(projectdir)")
