target("app.bridge.theme")
    set_kind("headeronly")
    add_includedirs("include", "../../framework/bridge", {public = true})
    add_packages("def_type", {public = true})

target("app.bridge.theme.test")
    set_kind("binary")
    set_default(false)
    add_deps("app.bridge.theme")
    add_files("tests/unit/theme_bridge_test.cpp")
    add_packages("catch2")
    set_rundir("$(projectdir)")
