target("app.bridge.todos")
    set_kind("headeronly")
    add_deps("lib.todos", {public = true})
    add_includedirs("include", "../../framework/bridge", {public = true})
    add_packages("def_type", {public = true})
