target("app.bridge.system")
    set_kind("static")
    add_rules("qt.static")
    add_files("src/*.cpp", "include/**.hpp")
    add_includedirs("include", {public = true})
    add_deps("app.bridge.todos")
    add_frameworks("QtCore", "QtGui", "QtWidgets", {public = true})
